name: UPDATE_APP_ACTION

on:
  push:
    branches:
      - main

jobs:
  update-readme-with-appinfo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Ensure public directory exists
        run: mkdir -p public

      - name: Inject API Key into JavaScript
        run: echo "const apiKey = '${{ secrets.MY_API_KEY }}';" > public/config.js

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: public
